# Generated by Django 4.1.5 on 2023-01-11 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ('-date_upload',)},
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=datetime.date(2023, 1, 11), upload_to=''),
            preserve_default=False,
        ),
    ]
